print("Hi, what is your name, age, DOB and what are some of your hobbies?")
print("What is your name")
name = input()
print("what is your age?")
age = input()
print("what is your date of birth?")
DOB = input()
print("what is your adress")
address = input()
print("what are your hobbies??")
hobbies = input()
print(f"My name is {name} my age is {age} my date of birth is {DOB} and my address is {address} {hobbies}")
print("Thankyou so much for your input")
